import { Words } from "../types/logic"

export const words: Words = {
  en: {
    easy: [
      "Angel",
      "Eyeball",
      "Pizza",
      "Angry",
      "Fireworks",
      "Pumpkin",
      "Baby",
      "Flower",
      "Rainbow",
      "Beard",
      "Flying saucer",
      "Recycle",
      "Bible",
      "Giraffe",
      "Sand castle",
      "Bikini",
      "Glasses",
      "Snowflake",
      "Book",
      "High heel",
      "Stairs",
      "Bucket",
      "Ice cream cone",
      "Starfish",
      "Bumblebee",
      "Igloo",
      "Strawberry",
      "Butterfly",
      "Ladybug",
      "Sun",
      "Camera",
      "Lamp",
      "Tire",
      "Cat",
      "Lion",
      "Toast",
      "Church",
      "Mailbox",
      "Toilet",
      "Coffee",
      "Nail",
      "Toothbrush",
      "Crayon",
      "Night",
      "Toothpaste",
      "Dog",
      "Nose",
      "Truck",
      "Dolphin",
      "Olympics",
      "Vase",
      "Egg",
      "Oreo",
      "Volleyball",
      "Eiffel Tower",
      "Peanut",
      "Wheel",
      "Sunflower",
      "Apple pie",
      "Snowman",
      "Hot dog",
      "Firetruck",
      "Banana",
      "Chair",
      "Balloon",
      "Carrot",
      "House",
      "Beach",
      "Tree",
      "Spoon",
      "Bed",
      "Fish",
      "Shirt",
      "Moon",
      "Cupcake",
      "Soccer ball",
      "Cookie",
      "Sun",
      "Apple",
      "Hat",
      "Boat",
      "Duck",
      "Pen",
      "Key",
      "Drum",
      "Clock",
      "Pizza slice",
      "Ice cube",
      "Window",
      "Bridge",
      "Bag",
      "Soap",
    ],
    medium: [
      "Abraham Lincoln",
      "Kiss",
      "Pigtails",
      "Brain",
      "Kitten",
      "Playground",
      "Bubble bath",
      "Kiwi",
      "Pumpkin pie",
      "Buckle",
      "Lipstick",
      "Raindrop",
      "Bus",
      "Lobster",
      "Robot",
      "Car accident",
      "Lollipop",
      "Salamander",
      "Castle",
      "Magnet",
      "Slipper",
      "Chainsaw",
      "Megaphone",
      "Snowball",
      "Circus tent",
      "Mermaid",
      "Sprinkler",
      "Computer",
      "Minivan",
      "Statue of Liberty",
      "Crib",
      "Mount Rushmore",
      "Tadpole",
      "Dragon",
      "Music",
      "Teepee",
      "Dumbbell",
      "North Pole",
      "Telescope",
      "Eel",
      "Nurse",
      "Tomato",
      "Elephant",
      "Onion",
      "Train",
      "Ferris wheel",
      "Owl",
      "Tricycle",
      "Flag",
      "Pacifier",
      "Tutu",
      "Golf",
      "Penny",
      "Umbrella",
      "Junk mail",
      "Piano",
      "Walrus",
      "Sherlock Holmes",
      "Waterfall",
      "Roller coaster",
      "Traffic jam",
      "Snow globe",
      "Jellyfish",
      "Garden gnome",
      "Firefighter",
      "Chocolate chip",
      "Skyscraper",
      "Kangaroo",
      "Video game",
      "Helicopter",
      "Bowling alley",
      "Farmer",
      "Popcorn",
      "Watermelon",
      "Headphones",
      "Treasure map",
      "Volcano",
      "Swing set",
      "Ice skating",
      "Superhero",
      "Skateboard",
      "Sushi",
      "Birthday cake",
      "Basketball",
      "Lightning",
      "Pancakes",
      "Dinosaur",
      "Police car",
      "Farmer's market",
      "Windmill",
      "Backpack",
      "Hot air balloon",
      "Fireplace",
      "Violin",
      "Train station",
      "Crocodile",
      "Unicorn",
    ],
    hard: [
      "Attic",
      "Glue",
      "Pocket watch",
      "Back seat",
      "High chair",
      "Rock band",
      "Birthday",
      "Hockey",
      "Sasquatch",
      "Black hole",
      "Hotel",
      "Scrambled eggs",
      "Blizzard",
      "Jump rope",
      "Seat belt",
      "Burrito",
      "Koala",
      "Skipping",
      "Captain",
      "Leprechaun",
      "Solar eclipse",
      "Chandelier",
      "Light",
      "Space",
      "Mask",
      "Stethoscope",
      "Cruise ship",
      "Mechanic",
      "Stork",
      "Dance",
      "Mom",
      "Sunburn",
      "Deodorant",
      "Mr. Potato Head",
      "Thread",
      "Einstein",
      "Narwhal",
      "Tourist",
      "Facebook",
      "Opera",
      "Trampoline",
      "Fever",
      "Pantyhose",
      "United States",
      "Flat",
      "Paper plate",
      "Universe",
      "Frame",
      "Photo",
      "Wi-Fi",
      "Full moon",
      "Pilgrim",
      "Yawn",
      "Game",
      "Pirate",
      "Zombie",
      "Recycling",
      "Time travel",
      "Optical illusion",
      "Leap year",
      "Great Wall of China",
      "Social media",
      "Hummingbird",
      "Metaphor",
      "Hitchhiking",
      "Archaeologist",
      "Mind reader",
      "Parallel universe",
      "Chain reaction",
      "Declaration of Independence",
      "Wireless charger",
      "Sandstorm",
      "Dreamcatcher",
      "Identity theft",
      "Brainstorm",
      "Artificial intelligence",
      "Polar vortex",
      "Quantum physics",
      "Fortune teller",
      "Tectonic plate",
      "Greenhouse effect",
      "Déjà vu",
      "Time capsule",
      "Human genome",
      "Virtual reality",
      "Masquerade ball",
      "Public speaking",
      "Supply and demand",
      "Rube Goldberg machine",
      "Moral dilemma",
      "Butterfly effect",
      "Subconscious",
      "Crop rotation",
      "String theory",
      "Eternal youth",
    ],
  },
  fr: {
    easy: [
      "Ange",
      "Globe oculaire",
      "Pizza",
      "En colère",
      "Feux d'artifice",
      "Citrouille",
      "Bébé",
      "Fleur",
      "Arc-en-ciel",
      "Barbe",
      "Soucoupe volante",
      "Recycler",
      "Bible",
      "Girafe",
      "Château de sable",
      "Bikini",
      "Lunettes",
      "Flocon de neige",
      "Livre",
      "Talon haut",
      "Escalier",
      "Seau",
      "Cornet de glace",
      "Étoile de mer",
      "Bourdon",
      "Igloo",
      "Fraise",
      "Papillon",
      "Coccinelle",
      "Soleil",
      "Appareil photo",
      "Lampe",
      "Pneu",
      "Chat",
      "Lion",
      "Toast",
      "Église",
      "Boîte aux lettres",
      "Toilette",
      "Café",
      "Clou",
      "Brosse à dents",
      "Crayon",
      "Nuit",
      "Dentifrice",
      "Chien",
      "Nez",
      "Camion",
      "Dauphin",
      "Jeux Olympiques",
      "Vase",
      "Oeuf",
      "Oreo",
      "Volley-ball",
      "Tour Eiffel",
      "Cacahuète",
      "Roue",
      "Tournesol",
      "Tarte aux pommes",
      "Bonhomme de neige",
      "Hot dog",
      "Camion de pompiers",
      "Banane",
      "Chaise",
      "Ballon",
      "Carotte",
      "Maison",
      "Plage",
      "Arbre",
      "Cuillère",
      "Lit",
      "Poisson",
      "Chemise",
      "Lune",
      "Cupcake",
      "Ballon de football",
      "Biscuit",
      "Soleil",
      "Pomme",
      "Chapeau",
      "Bateau",
      "Canard",
      "Stylo",
      "Clé",
      "Tambour",
      "Horloge",
      "Part de pizza",
      "Glacon",
      "Fenêtre",
      "Pont",
      "Sac",
      "Savon",
    ],
    medium: [
      "Abraham Lincoln",
      "Baiser",
      "Couettes",
      "Cerveau",
      "Chaton",
      "Aire de jeux",
      "Bain moussant",
      "Kiwi",
      "Tarte à la citrouille",
      "Boucle",
      "Rouge à lèvres",
      "Goutte de pluie",
      "Bus",
      "Homard",
      "Robot",
      "Accident de voiture",
      "Sucette",
      "Salamandre",
      "Château",
      "Aimant",
      "Pantoufle",
      "Tronçonneuse",
      "Mégaphone",
      "Boule de neige",
      "Chapiteau",
      "Sirène",
      "Arroseur",
      "Ordinateur",
      "Monospace",
      "Statue de la Liberté",
      "Berceau",
      "Mont Rushmore",
      "Têtard",
      "Dragon",
      "Musique",
      "Tipi",
      "Haltère",
      "Pôle Nord",
      "Télescope",
      "Anguille",
      "Infirmière",
      "Tomate",
      "Éléphant",
      "Oignon",
      "Train",
      "Grande roue",
      "Hibou",
      "Tricycle",
      "Drapeau",
      "Tétine",
      "Tutu",
      "Golf",
      "Sou",
      "Parapluie",
      "Publicité",
      "Piano",
      "Morse",
      "Sherlock Holmes",
      "Cascade",
      "Montagnes russes",
      "Bouchon de circulation",
      "Boule à neige",
      "Méduse",
      "Nain de jardin",
      "Pompier",
      "Pépite de chocolat",
      "Gratte-ciel",
      "Kangourou",
      "Jeu vidéo",
      "Hélicoptère",
      "Bowling",
      "Agriculteur",
      "Pop-corn",
      "Pastèque",
      "Casque audio",
      "Carte au trésor",
      "Volcan",
      "Balancelle",
      "Patinage sur glace",
      "Super-héros",
      "Skateboard",
      "Sushi",
      "Gâteau d'anniversaire",
      "Basket-ball",
      "Éclair",
      "Crêpes",
      "Dinosaur",
      "Voiture de police",
      "Marché fermier",
      "Moulin à vent",
      "Sac à dos",
      "Montgolfière",
      "Cheminée",
      "Violon",
      "Gare",
      "Crocodile",
      "Licorne",
    ],
    hard: [
      "Grenier",
      "Colle",
      "Montre de poche",
      "Banquette arrière",
      "Chaise haute",
      "Groupe de rock",
      "Anniversaire",
      "Hockey",
      "Sasquatch",
      "Trou noir",
      "Hôtel",
      "Oeufs brouillés",
      "Tempête de neige",
      "Corde à sauter",
      "Ceinture de sécurité",
      "Burrito",
      "Koala",
      "Saut à la corde",
      "Capitaine",
      "Farfadet",
      "Éclipse solaire",
      "Lustre",
      "Lumière",
      "Espace",
      "Masque",
      "Stéthoscope",
      "Paquebot de croisière",
      "Mécanicien",
      "Cigogne",
      "Danse",
      "Maman",
      "Coup de soleil",
      "Déodorant",
      "Monsieur Patate",
      "Fil",
      "Einstein",
      "Narval",
      "Touriste",
      "Facebook",
      "Opéra",
      "Trampoline",
      "Fièvre",
      "Collants",
      "États-Unis",
      "Appartement",
      "Assiette en papier",
      "Univers",
      "Cadre",
      "Photo",
      "Wi-Fi",
      "Pleine lune",
      "Pèlerin",
      "Bâiller",
      "Jeu",
      "Pirate",
      "Zombie",
      "Recyclage",
      "Voyage dans le temps",
      "Illusion d'optique",
      "Année bissextile",
      "Grande Muraille de Chine",
      "Réseaux sociaux",
      "Colibri",
      "Métaphore",
      "Auto-stop",
      "Archéologue",
      "Lecteur de pensées",
      "Univers parallèle",
      "Réaction en chaîne",
      "Déclaration d'indépendance",
      "Chargeur sans fil",
      "Tempête de sable",
      "Attrape-rêves",
      "Usurpation d'identité",
      "Remue-méninges",
      "Intelligence artificielle",
      "Vortex polaire",
      "Physique quantique",
      "Voyant",
      "Plaque tectonique",
      "Effet de serre",
      "Déjà vu",
      "Capsule temporelle",
      "Génome humain",
      "Réalité virtuelle",
      "Bal masqué",
      "Prise de parole en public",
      "Offre et demande",
      "Machine de Rube Goldberg",
      "Dilemme moral",
      "Effet papillon",
      "Subconscient",
      "Rotation des cultures",
      "Théorie des cordes",
      "Jeunesse éternelle",
    ],
  },
  ru: {
    easy: [
      "Ангел",
      "Глазное яблоко",
      "Пицца",
      "Сердитый",
      "Фейерверк",
      "Тыква",
      "Младенец",
      "Цветок",
      "Радуга",
      "Борода",
      "Летающая тарелка",
      "Перерабатывать",
      "Библия",
      "Жираф",
      "Песочный замок",
      "Бикини",
      "Очки",
      "Снежинка",
      "Книга",
      "Туфель на высоком каблуке",
      "Лестница",
      "Ведро",
      "Мороженое",
      "Морская звезда",
      "Шмель",
      "Иглу",
      "Клубника",
      "Бабочка",
      "Божья коровка",
      "Солнце",
      "Камера",
      "Лампа",
      "Шина",
      "Кошка",
      "Лев",
      "Тост",
      "Церковь",
      "Почтовый ящик",
      "Туалет",
      "Кофе",
      "Гвоздь",
      "Зубная щетка",
      "Мелок",
      "Ночь",
      "Зубная паста",
      "Собака",
      "Нос",
      "Грузовик",
      "Дельфин",
      "Олимпийские игры",
      "Ваза",
      "Яйцо",
      "Орео",
      "Волейбол",
      "Эйфелева башня",
      "Арахис",
      "Колесо",
      "Подсолнух",
      "Яблочный пирог",
      "Снеговик",
      "Хот-дог",
      "Пожарная машина",
      "Банан",
      "Стул",
      "Шарик",
      "Морковь",
      "Дом",
      "Пляж",
      "Дерево",
      "Ложка",
      "Кровать",
      "Рыба",
      "Рубашка",
      "Луна",
      "Капкейк",
      "Футбольный мяч",
      "Печенье",
      "Солнце",
      "Яблоко",
      "Шляпа",
      "Лодка",
      "Утка",
      "Ручка",
      "Ключ",
      "Барабан",
      "Часы",
      "Кусок пиццы",
      "Ледяной кубик",
      "Окно",
      "Мост",
      "Сумка",
      "Мыло",
    ],
    medium: [
      "Авраам Линкольн",
      "Поцелуй",
      "Косички",
      "Мозг",
      "Котёнок",
      "Игровая площадка",
      "Пенистая ванна",
      "Киви",
      "Тыквенный пирог",
      "Пряжка",
      "Помада",
      "Капля дождя",
      "Автобус",
      "Омар",
      "Робот",
      "Автомобильная авария",
      "Леденец",
      "Саламандра",
      "Замок",
      "Магнит",
      "Тапочка",
      "Бензопила",
      "Мегафон",
      "Снежок",
      "Цирковой шатер",
      "Русалка",
      "Разбрызгиватель",
      "Компьютер",
      "Минивэн",
      "Статуя Свободы",
      "Детская кроватка",
      "Гора Рашмор",
      "Головастик",
      "Дракон",
      "Музыка",
      "Типи",
      "Гантель",
      "Северный полюс",
      "Телескоп",
      "Угорь",
      "Медсестра",
      "Томат",
      "Слон",
      "Лук",
      "Поезд",
      "Чёртово колесо",
      "Сова",
      "Трёхколёсный велосипед",
      "Флаг",
      "Соска",
      "Пачка",
      "Гольф",
      "Монета",
      "Зонтик",
      "Ненужная почта",
      "Пианино",
      "Морж",
      "Sherlock Holmes",
      "Водопад",
      "Американские горки",
      "Пробка",
      "Снежный глобус",
      "Медуза",
      "Садовый гном",
      "Пожарный",
      "Шоколадная капля",
      "Небоскрёб",
      "Кенгуру",
      "Видеоигра",
      "Вертолёт",
      "Боулинг",
      "Фермер",
      "Попкорн",
      "Арбуз",
      "Наушники",
      "Карта сокровищ",
      "Вулкан",
      "Качели",
      "Катание на коньках",
      "Супергерой",
      "Скейтборд",
      "Суши",
      "Торт на день рождения",
      "Баскетбол",
      "Молния",
      "Блины",
      "Динозавр",
      "Полицейская машина",
      "Фермерский рынок",
      "Ветряная мельница",
      "Рюкзак",
      "Воздушный шар",
      "Камин",
      "Скрипка",
      "Железнодорожный вокзал",
      "Крокодил",
      "Единорог",
    ],
    hard: [
      "Чердак",
      "Клей",
      "Карманные часы",
      "Заднее сиденье",
      "Детский стульчик",
      "Рок-группа",
      "День рождения",
      "Хоккей",
      "Сасквоч",
      "Чёрная дыра",
      "Отель",
      "Яичница-болтунья",
      "Буран",
      "Скакалка",
      "Ремень безопасности",
      "Буррито",
      "Коала",
      "Прыжки",
      "Капитан",
      "Лепрекон",
      "Солнечное затмение",
      "Люстра",
      "Свет",
      "Космос",
      "Маска",
      "Стетоскоп",
      "Круизный лайнер",
      "Механик",
      "Аист",
      "Танец",
      "Мама",
      "Солнечный ожог",
      "Дезодорант",
      "Мистер Картофельная Голова",
      "Нить",
      "Эйнштейн",
      "Нарвал",
      "Турист",
      "Фейсбук",
      "Опера",
      "Батут",
      "Жар",
      "Колготки",
      "Соединённые Штаты",
      "Квартира",
      "Бумажная тарелка",
      "Вселенная",
      "Рамка",
      "Фото",
      "Вай-фай",
      "Полнолуние",
      "Пилигрим",
      "Зевок",
      "Игра",
      "Пират",
      "Зомби",
      "Переработка",
      "Путешествие во времени",
      "Оптическая иллюзия",
      "Високосный год",
      "Великая китайская стена",
      "Социальные сети",
      "Колибри",
      "Метафора",
      "Путешествие автостопом",
      "Археолог",
      "Чтец мыслей",
      "Параллельная вселенная",
      "Цепная реакция",
      "Декларация независимости",
      "Беспроводная зарядка",
      "Песчаная буря",
      "Ловец снов",
      "Кража личных данных",
      "Мозговой штурм",
      "Искусственный интеллект",
      "Полярный вихрь",
      "Квантовая физика",
      "Гадалка",
      "Тектоническая плита",
      "Парниковый эффект",
      "Дежавю",
      "Капсула времени",
      "Человеческий геном",
      "Виртуальная реальность",
      "Маскарадный бал",
      "Публичные выступления",
      "Спрос и предложение",
      "Машина Руба Голдберга",
      "Моральная дилемма",
      "Эффект бабочки",
      "Подсознание",
      "Севооборот",
      "Теория струн",
      "Вечная молодость",
    ],
  },
  es: {
    easy: [
      "Ángel",
      "Ojo",
      "Pizza",
      "Enojado",
      "Fuegos artificiales",
      "Calabaza",
      "Bebé",
      "Flor",
      "Arcoíris",
      "Barba",
      "Platillo volador",
      "Reciclar",
      "Biblia",
      "Jirafa",
      "Castillo de arena",
      "Bikini",
      "Gafas",
      "Copo de nieve",
      "Libro",
      "Tacón alto",
      "Escaleras",
      "Cubo",
      "Cono de helado",
      "Estrella de mar",
      "Abejorro",
      "Iglú",
      "Fresa",
      "Mariposa",
      "Mariquita",
      "Sol",
      "Cámara",
      "Lámpara",
      "Neumático",
      "Gato",
      "León",
      "Tostada",
      "Iglesia",
      "Buzón",
      "Inodoro",
      "Café",
      "Uña",
      "Cepillo de dientes",
      "Crayón",
      "Noche",
      "Pasta de dientes",
      "Perro",
      "Nariz",
      "Camión",
      "Delfín",
      "Olimpiadas",
      "Jarrón",
      "Huevo",
      "Oreo",
      "Voleibol",
      "Torre Eiffel",
      "Cacahuate",
      "Rueda",
      "Girasol",
      "Pastel de manzana",
      "Muñeco de nieve",
      "Perro caliente",
      "Camión de bomberos",
      "Plátano",
      "Silla",
      "Globo",
      "Zanahoria",
      "Casa",
      "Playa",
      "Árbol",
      "Cuchara",
      "Cama",
      "Pez",
      "Camisa",
      "Luna",
      "Cupcake",
      "Balón de fútbol",
      "Galleta",
      "Sol",
      "Manzana",
      "Sombrero",
      "Barco",
      "Pato",
      "Bolígrafo",
      "Llave",
      "Tambor",
      "Reloj",
      "Rebanada de pizza",
      "Cubito de hielo",
      "Ventana",
      "Puente",
      "Bolsa",
      "Jabón",
    ],
    medium: [
      "Abraham Lincoln",
      "Beso",
      "Coletas",
      "Cerebro",
      "Gatito",
      "Parque infantil",
      "Baño de burbujas",
      "Kiwi",
      "Pastel de calabaza",
      "Hebilla",
      "Lápiz labial",
      "Gota de lluvia",
      "Autobús",
      "Langosta",
      "Robot",
      "Accidente de coche",
      "Piruleta",
      "Salamandra",
      "Castillo",
      "Imán",
      "Zapatilla",
      "Motosierra",
      "Megáfono",
      "Bola de nieve",
      "Carpa de circo",
      "Sirena",
      "Aspersor",
      "Computadora",
      "Miniván",
      "Estatua de la Libertad",
      "Cuna",
      "Monte Rushmore",
      "Renacuajo",
      "Dragón",
      "Música",
      "Tienda de campaña",
      "Mancuerna",
      "Polo Norte",
      "Telescopio",
      "Anguila",
      "Enfermera",
      "Tomate",
      "Elefante",
      "Cebolla",
      "Tren",
      "Noria",
      "Búho",
      "Triciclo",
      "Bandera",
      "Chupete",
      "Tutu",
      "Golf",
      "Centavo",
      "Paraguas",
      "Correo basura",
      "Piano",
      "Morsa",
      "Sherlock Holmes",
      "Cascada",
      "Montaña rusa",
      "Atasco",
      "Bola de nieve",
      "Medusa",
      "Enano de jardín",
      "Bombero",
      "Chispas de chocolate",
      "Rascacielos",
      "Canguro",
      "Videojuego",
      "Helicóptero",
      "Pista de bolos",
      "Granjero",
      "Palomitas de maíz",
      "Sandía",
      "Auriculares",
      "Mapa del tesoro",
      "Volcán",
      "Columpios",
      "Patinaje sobre hielo",
      "Súperhéroe",
      "Patinete",
      "Sushi",
      "Tarta de cumpleaños",
      "Baloncesto",
      "Relámpago",
      "Panqueques",
      "Dinosaurio",
      "Coche de policía",
      "Mercado de agricultores",
      "Molino de viento",
      "Mochila",
      "Globo aerostático",
      "Chimenea",
      "Violín",
      "Estación de tren",
      "Cocodrilo",
      "Unicornio",
    ],
    hard: [
      "Ático",
      "Pegamento",
      "Reloj de bolsillo",
      "Asiento trasero",
      "Silla alta",
      "Banda de rock",
      "Cumpleaños",
      "Hockey",
      "Sasquatch",
      "Agujero negro",
      "Hotel",
      "Huevos revueltos",
      "Tormenta de nieve",
      "Cuerda para saltar",
      "Cinturón de seguridad",
      "Burrito",
      "Koala",
      "Saltar",
      "Capitán",
      "Duende",
      "Eclipse solar",
      "Candelabro",
      "Luz",
      "Espacio",
      "Máscara",
      "Estetoscopio",
      "Barco de crucero",
      "Mecánico",
      "Cigüeña",
      "Baile",
      "Mamá",
      "Quemadura solar",
      "Desodorante",
      "Señor Cara de Papa",
      "Hilo",
      "Einstein",
      "Narval",
      "Turista",
      "Facebook",
      "Ópera",
      "Trampolín",
      "Fiebre",
      "Medias",
      "Estados Unidos",
      "Plano",
      "Plato de papel",
      "Universo",
      "Marco",
      "Foto",
      "Wi-Fi",
      "Luna llena",
      "Pilgrim",
      "Bostezo",
      "Juego",
      "Pirata",
      "Zombi",
      "Reciclaje",
      "Viaje en el tiempo",
      "Ilusión óptica",
      "Año bisiesto",
      "Gran Muralla China",
      "Redes sociales",
      "Colibrí",
      "Metáfora",
      "Hacer autoestop",
      "Arqueólogo",
      "Lectura de mentes",
      "Universo paralelo",
      "Reacción en cadena",
      "Declaración de independencia",
      "Cargador inalámbrico",
      "Tormenta de arena",
      "Atrapasueños",
      "Robo de identidad",
      "Lluvia de ideas",
      "Inteligencia artificial",
      "Vórtice polar",
      "Física cuántica",
      "Adivina",
      "Placa tectónica",
      "Efecto invernadero",
      "Déjà vu",
      "Cápsula del tiempo",
      "Genoma humano",
      "Realidad virtual",
      "Baile de máscaras",
      "Oratoria",
      "Oferta y demanda",
      "Máquina de Rube Goldberg",
      "Dilema moral",
      "Efecto mariposa",
      "Subconsciente",
      "Rotación de cultivos",
      "Teoría de cuerdas",
      "Juventud eterna",
    ],
  },
  pt: {
    easy: [
      "Anjo",
      "Olho",
      "Pizza",
      "Bravo",
      "Fogos de artifício",
      "Abóbora",
      "Bebê",
      "Flor",
      "Arco-íris",
      "Barba",
      "Disco voador",
      "Reciclar",
      "Bíblia",
      "Girafa",
      "Castelo de areia",
      "Biquíni",
      "Óculos",
      "Floco de neve",
      "Livro",
      "Salto alto",
      "Escadas",
      "Balde",
      "Casquinha de sorvete",
      "Estrela-do-mar",
      "Abelha",
      "Iglu",
      "Morango",
      "Borboleta",
      "Joaninha",
      "Sol",
      "Câmera",
      "Lâmpada",
      "Pneu",
      "Gato",
      "Leão",
      "Torrada",
      "Igreja",
      "Caixa de correio",
      "Vaso sanitário",
      "Café",
      "Unha",
      "Escova de dentes",
      "Giz de cera",
      "Noite",
      "Creme dental",
      "Cachorro",
      "Nariz",
      "Caminhão",
      "Golfinho",
      "Olimpíadas",
      "Vaso",
      "Ovo",
      "Oreo",
      "Vôlei",
      "Torre Eiffel",
      "Amendoim",
      "Roda",
      "Girassol",
      "Torta de maçã",
      "Boneco de neve",
      "Cachorro-quente",
      "Caminhão de bombeiros",
      "Banana",
      "Cadeira",
      "Balão",
      "Cenoura",
      "Casa",
      "Praia",
      "Árvore",
      "Colher",
      "Cama",
      "Peixe",
      "Camisa",
      "Lua",
      "Cupcake",
      "Bola de futebol",
      "Biscoito",
      "Sol",
      "Maçã",
      "Chapéu",
      "Barco",
      "Pato",
      "Caneta",
      "Chave",
      "Tambor",
      "Relógio",
      "Fatia de pizza",
      "Cubo de gelo",
      "Janela",
      "Ponte",
      "Bolsa",
      "Sabão",
    ],
    medium: [
      "Abraham Lincoln",
      "Beijo",
      "Rabo de cavalo",
      "Cérebro",
      "Gatinho",
      "Parque infantil",
      "Banho de espuma",
      "Kiwi",
      "Torta de abóbora",
      "Fivela",
      "Batom",
      "Gota de chuva",
      "Ônibus",
      "Lagosta",
      "Robô",
      "Acidente de carro",
      "Pirulito",
      "Salamandra",
      "Castelo",
      "Ímã",
      "Chinelo",
      "Serra elétrica",
      "Megafone",
      "Bola de neve",
      "Tenda de circo",
      "Sereia",
      "Sprinkler",
      "Computador",
      "Minivan",
      "Estátua da Liberdade",
      "Berço",
      "Monte Rushmore",
      "Girino",
      "Dragão",
      "Música",
      "Tenda",
      "Halter",
      "Polo Norte",
      "Telescópio",
      "Enguia",
      "Enfermeira",
      "Tomate",
      "Elefante",
      "Cebola",
      "Trem",
      "Roda-gigante",
      "Coruja",
      "Triciclo",
      "Bandeira",
      "Chupeta",
      "Tutu",
      "Golfe",
      "Moeda",
      "Guarda-chuva",
      "Correio indesejado",
      "Piano",
      "Morsa",
      "Sherlock Holmes",
      "Cachoeira",
      "Montanha-russa",
      "Engarrafamento",
      "Globo de neve",
      "Água-viva",
      "Anão de jardim",
      "Bombeiro",
      "Pedaço de chocolate",
      "Arranha-céu",
      "Canguru",
      "Jogo de vídeo",
      "Helicóptero",
      "Pista de boliche",
      "Fazendeiro",
      "pipoca",
      "Melancia",
      "Fones de ouvido",
      "Mapa do tesouro",
      "Vulcão",
      "Baloiço",
      "Patinação no gelo",
      "Super-herói",
      "Skate",
      "Sushi",
      "Bolo de aniversário",
      "Basquete",
      "Raio",
      "Panqueca",
      "Dinossauro",
      "Carro de polícia",
      "Mercado de agricultores",
      "Moinho de vento",
      "Mochila",
      "Balão de ar quente",
      "Lareira",
      "Violino",
      "Estação de trem",
      "Crocodilo",
      "Unicórnio",
    ],
    hard: [
      "Sótão",
      "Cola",
      "Relógio de bolso",
      "Banco traseiro",
      "Cadeira alta",
      "Banda de rock",
      "Aniversário",
      "Hóquei",
      "Pé grande",
      "Buraco negro",
      "Hotel",
      "Ovo mexido",
      "Tempestade de neve",
      "Corda",
      "Cinto de segurança",
      "Burrito",
      "Coala",
      "Pular",
      "Capitão",
      "Duende",
      "Eclipse solar",
      "Candelabro",
      "Luz",
      "Espaço",
      "Máscara",
      "Estetoscópio",
      "Navio de cruzeiro",
      "Mecânico",
      "Cegonha",
      "Dança",
      "Mãe",
      "Queimadura solar",
      "Desodorante",
      "Sr. Cabeça de Batata",
      "Linha",
      "Einstein",
      "Narval",
      "Turista",
      "Facebook",
      "Ópera",
      "Trampolim",
      "Febre",
      "Meia-calça",
      "Estados Unidos",
      "Apartamento",
      "Prato de papel",
      "Universo",
      "Moldura",
      "Foto",
      "Wi-Fi",
      "Lua cheia",
      "Peregrino",
      "Bocejo",
      "Jogo",
      "Pirata",
      "Zumbi",
      "Reciclagem",
      "Viagem no tempo",
      "Ilusão de ótica",
      "Ano bissexto",
      "Grande Muralha da China",
      "Mídias sociais",
      "Beija-flor",
      "Metáfora",
      "Carona",
      "Arqueólogo",
      "Leitor de mentes",
      "Universo paralelo",
      "Reação em cadeia",
      "Declaração de Independência",
      "Carregador sem fio",
      "Tempestade de areia",
      "Apanhador de sonhos",
      "Roubo de identidade",
      "Tempestade de ideias",
      "Inteligência artificial",
      "Vórtice polar",
      "Física quântica",
      "Vidente",
      "Placa tectônica",
      "Efeito estufa",
      "Déjà vu",
      "Cápsula do tempo",
      "Genoma humano",
      "Realidade virtual",
      "Baile de máscaras",
      "Fala em público",
      "Oferta e demanda",
      "Máquina de Rube Goldberg",
      "Dilema moral",
      "Efeito borboleta",
      "Subconsciente",
      "Rotação de culturas",
      "Teoria das cordas",
      "Juventude eterna",
    ],
  },
  cn: {
    easy: [
      "天使",
      "眼球",
      "披萨",
      "生气",
      "烟花",
      "南瓜",
      "婴儿",
      "花",
      "彩虹",
      "胡子",
      "飞碟",
      "回收",
      "圣经",
      "长颈鹿",
      "沙堡",
      "比基尼",
      "眼镜",
      "雪花",
      "书",
      "高跟鞋",
      "楼梯",
      "桶",
      "冰淇淋蛋筒",
      "海星",
      "大黄蜂",
      "冰屋",
      "草莓",
      "蝴蝶",
      "瓢虫",
      "太阳",
      "相机",
      "灯",
      "轮胎",
      "猫",
      "狮子",
      "吐司",
      "教堂",
      "邮箱",
      "厕所",
      "咖啡",
      "钉子",
      "牙刷",
      "蜡笔",
      "夜晚",
      "牙膏",
      "狗",
      "鼻子",
      "卡车",
      "海豚",
      "奥运会",
      "花瓶",
      "鸡蛋",
      "奥利奥",
      "排球",
      "埃菲尔铁塔",
      "花生",
      "轮子",
      "向日葵",
      "苹果派",
      "雪人",
      "热狗",
      "消防车",
      "香蕉",
      "椅子",
      "气球",
      "胡萝卜",
      "房子",
      "海滩",
      "树",
      "勺子",
      "床",
      "鱼",
      "衬衫",
      "月亮",
      "纸杯蛋糕",
      "足球",
      "饼干",
      "太阳",
      "苹果",
      "帽子",
      "船",
      "鸭子",
      "笔",
      "钥匙",
      "鼓",
      "时钟",
      "披萨片",
      "冰块",
      "窗户",
      "桥",
      "包",
      "肥皂",
    ],
    medium: [
      "亚伯拉罕·林肯",
      "亲吻",
      "辫子",
      "大脑",
      "小猫",
      "操场",
      "泡泡浴",
      "奇异果",
      "南瓜派",
      "扣子",
      "口红",
      "雨滴",
      "公共汽车",
      "龙虾",
      "机器人",
      "车祸",
      "棒棒糖",
      "蝾螈",
      "城堡",
      "磁铁",
      "拖鞋",
      "电锯",
      "扩音器",
      "雪球",
      "马戏团帐篷",
      "美人鱼",
      "洒水器",
      "电脑",
      "小型货车",
      "自由女神像",
      "婴儿床",
      "拉什莫尔山",
      "蝌蚪",
      "龙",
      "音乐",
      "圆锥帐篷",
      "哑铃",
      "北极",
      "望远镜",
      "鳗鱼",
      "护士",
      "西红柿",
      "大象",
      "洋葱",
      "火车",
      "摩天轮",
      "猫头鹰",
      "三轮车",
      "旗子",
      "奶嘴",
      "芭蕾舞短裙",
      "高尔夫",
      "便士",
      "雨伞",
      "垃圾邮件",
      "钢琴",
      "海象",
      "Sherlock Holmes",
      "瀑布",
      "过山车",
      "交通堵塞",
      "雪花球",
      "水母",
      "花园侏儒",
      "消防员",
      "巧克力片",
      "摩天大楼",
      "袋鼠",
      "视频游戏",
      "直升机",
      "保龄球场",
      "农民",
      "爆米花",
      "西瓜",
      "耳机",
      "藏宝图",
      "火山",
      "秋千",
      "滑冰",
      "超级英雄",
      "滑板",
      "寿司",
      "生日蛋糕",
      "篮球",
      "闪电",
      "煎饼",
      "恐龙",
      "警车",
      "农贸市场",
      "风车",
      "背包",
      "热气球",
      "壁炉",
      "小提琴",
      "火车站",
      "鳄鱼",
      "独角兽",
    ],
    hard: [
      "阁楼",
      "胶水",
      "怀表",
      "后座",
      "高脚椅",
      "摇滚乐队",
      "生日",
      "曲棍球",
      "大脚怪",
      "黑洞",
      "酒店",
      "炒蛋",
      "暴风雪",
      "跳绳",
      "安全带",
      "卷饼",
      "考拉",
      "跳跃",
      "船长",
      "妖精",
      "日食",
      "吊灯",
      "光",
      "太空",
      "面具",
      "听诊器",
      "游轮",
      "机械师",
      "鹳",
      "舞蹈",
      "妈妈",
      "晒伤",
      "除臭剂",
      "土豆头先生",
      "线",
      "爱因斯坦",
      "独角鲸",
      "游客",
      "脸书",
      "歌剧",
      "蹦床",
      "发烧",
      "连裤袜",
      "美国",
      "公寓",
      "纸盘",
      "宇宙",
      "相框",
      "照片",
      "Wi-Fi",
      "满月",
      "朝圣者",
      "打哈欠",
      "游戏",
      "海盗",
      "僵尸",
      "回收",
      "时间旅行",
      "视觉错觉",
      "闰年",
      "长城",
      "社交媒体",
      "蜂鸟",
      "隐喻",
      "搭便车",
      "考古学家",
      "读心术",
      "平行宇宙",
      "链式反应",
      "独立宣言",
      "无线充电器",
      "沙尘暴",
      "捕梦网",
      "身份盗窃",
      "头脑风暴",
      "人工智能",
      "极地涡旋",
      "量子物理",
      "算命师",
      "构造板块",
      "温室效应",
      "似曾相识",
      "时间胶囊",
      "人类基因组",
      "虚拟现实",
      "化装舞会",
      "公共演讲",
      "供求关系",
      "鲁布·戈德堡机器",
      "道德困境",
      "蝴蝶效应",
      "潜意识",
      "轮作",
      "弦理论",
      "永恒的青春",
    ],
  },
}
