import { Words } from "../types/logic"

export const words: Words = {
  en: {
    easy: [
      "Angel",
      "Eyeball",
      "Pizza",
      "Angry",
      "Fireworks",
      "Pumpkin",
      "Baby",
      "Flower",
      "Rainbow",
      "Beard",
      "Flying saucer",
      "Recycle",
      "Bible",
      "Giraffe",
      "Sand castle",
      "Bikini",
      "Glasses",
      "Snowflake",
      "Book",
      "High heel",
      "Stairs",
      "Bucket",
      "Ice cream cone",
      "Starfish",
      "Bumblebee",
      "Igloo",
      "Strawberry",
      "Butterfly",
      "Ladybug",
      "Sun",
      "Camera",
      "Lamp",
      "Tire",
      "Cat",
      "Lion",
      "Toast",
      "Church",
      "Mailbox",
      "Toilet",
      "Coffee",
      "Nail",
      "Toothbrush",
      "Crayon",
      "Night",
      "Toothpaste",
      "Dog",
      "Nose",
      "Truck",
      "Dolphin",
      "Olympics",
      "Vase",
      "Egg",
      "Oreo",
      "Volleyball",
      "Eiffel Tower",
      "Peanut",
      "Wheel",
    ],
    medium: [
      "Abraham Lincoln",
      "Kiss",
      "Pigtails",
      "Brain",
      "Kitten",
      "Playground",
      "Bubble bath",
      "Kiwi",
      "Pumpkin pie",
      "Buckle",
      "Lipstick",
      "Raindrop",
      "Bus",
      "Lobster",
      "Robot",
      "Car accident",
      "Lollipop",
      "Salamander",
      "Castle",
      "Magnet",
      "Slipper",
      "Chainsaw",
      "Megaphone",
      "Snowball",
      "Circus tent",
      "Mermaid",
      "Sprinkler",
      "Computer",
      "Minivan",
      "Statue of Liberty",
      "Crib",
      "Mount Rushmore",
      "Tadpole",
      "Dragon",
      "Music",
      "Teepee",
      "Dumbbell",
      "North Pole",
      "Telescope",
      "Eel",
      "Nurse",
      "Tomato",
      "Elephant",
      "Onion",
      "Train",
      "Ferris wheel",
      "Owl",
      "Tricycle",
      "Flag",
      "Pacifier",
      "Tutu",
      "Golf",
      "Penny",
      "Umbrella",
      "Junk mail",
      "Piano",
      "Walrus",
    ],
    hard: [
      "Attic",
      "Glue",
      "Pocket watch",
      "Back seat",
      "High chair",
      "Rock band",
      "Birthday",
      "Hockey",
      "Sasquatch",
      "Black hole",
      "Hotel",
      "Scrambled eggs",
      "Blizzard",
      "Jump rope",
      "Seat belt",
      "Burrito",
      "Koala",
      "Skipping",
      "Captain",
      "Leprechaun",
      "Solar eclipse",
      "Chandelier",
      "Light",
      "Space",
      "Crib",
      "Mask",
      "Stethoscope",
      "Cruise ship",
      "Mechanic",
      "Stork",
      "Dance",
      "Mom",
      "Sunburn",
      "Deodorant",
      "Mr. Potato Head",
      "Thread",
      "Einstein",
      "Narwhal",
      "Tourist",
      "Facebook",
      "Opera",
      "Trampoline",
      "Fever",
      "Pantyhose",
      "United States",
      "Flat",
      "Paper plate",
      "Universe",
      "Frame",
      "Photo",
      "Wi-Fi",
      "Full moon",
      "Pilgrim",
      "Yawn",
      "Game",
      "Pirate",
      "Zombie",
    ],
  },
  fr: {
    easy: [
      "Ange",
      "Globe oculaire",
      "Pizza",
      "En colère",
      "Feux d'artifice",
      "Citrouille",
      "Bébé",
      "Fleur",
      "Arc-en-ciel",
      "Barbe",
      "Soucoupe volante",
      "Recycler",
      "Bible",
      "Girafe",
      "Château de sable",
      "Bikini",
      "Lunettes",
      "Flocon de neige",
      "Livre",
      "Talon haut",
      "Escalier",
      "Seau",
      "Cornet de glace",
      "Étoile de mer",
      "Bourdon",
      "Igloo",
      "Fraise",
      "Papillon",
      "Coccinelle",
      "Soleil",
      "Appareil photo",
      "Lampe",
      "Pneu",
      "Chat",
      "Lion",
      "Toast",
      "Église",
      "Boîte aux lettres",
      "Toilette",
      "Café",
      "Clou",
      "Brosse à dents",
      "Crayon",
      "Nuit",
      "Dentifrice",
      "Chien",
      "Nez",
      "Camion",
      "Dauphin",
      "Jeux Olympiques",
      "Vase",
      "Oeuf",
      "Oreo",
      "Volley-ball",
      "Tour Eiffel",
      "Cacahuète",
      "Roue",
    ],
    medium: [
      "Abraham Lincoln",
      "Baiser",
      "Couettes",
      "Cerveau",
      "Chaton",
      "Aire de jeux",
      "Bain moussant",
      "Kiwi",
      "Tarte à la citrouille",
      "Boucle",
      "Rouge à lèvres",
      "Goutte de pluie",
      "Bus",
      "Homard",
      "Robot",
      "Accident de voiture",
      "Sucette",
      "Salamandre",
      "Château",
      "Aimant",
      "Pantoufle",
      "Tronçonneuse",
      "Mégaphone",
      "Boule de neige",
      "Chapiteau",
      "Sirène",
      "Arroseur",
      "Ordinateur",
      "Monospace",
      "Statue de la Liberté",
      "Berceau",
      "Mont Rushmore",
      "Têtard",
      "Dragon",
      "Musique",
      "Tipi",
      "Haltère",
      "Pôle Nord",
      "Télescope",
      "Anguille",
      "Infirmière",
      "Tomate",
      "Éléphant",
      "Oignon",
      "Train",
      "Grande roue",
      "Hibou",
      "Tricycle",
      "Drapeau",
      "Tétine",
      "Tutu",
      "Golf",
      "Sou",
      "Parapluie",
      "Publicité",
      "Piano",
      "Morse",
    ],
    hard: [
      "Grenier",
      "Colle",
      "Montre de poche",
      "Banquette arrière",
      "Chaise haute",
      "Groupe de rock",
      "Anniversaire",
      "Hockey",
      "Sasquatch",
      "Trou noir",
      "Hôtel",
      "Oeufs brouillés",
      "Tempête de neige",
      "Corde à sauter",
      "Ceinture de sécurité",
      "Burrito",
      "Koala",
      "Saut à la corde",
      "Capitaine",
      "Farfadet",
      "Éclipse solaire",
      "Lustre",
      "Lumière",
      "Espace",
      "Masque",
      "Stéthoscope",
      "Paquebot de croisière",
      "Mécanicien",
      "Cigogne",
      "Danse",
      "Maman",
      "Coup de soleil",
      "Déodorant",
      "Monsieur Patate",
      "Fil",
      "Einstein",
      "Narval",
      "Touriste",
      "Facebook",
      "Opéra",
      "Trampoline",
      "Fièvre",
      "Collants",
      "États-Unis",
      "Appartement",
      "Assiette en papier",
      "Univers",
      "Cadre",
      "Photo",
      "Wi-Fi",
      "Pleine lune",
      "Pèlerin",
      "Bâiller",
      "Jeu",
      "Pirate",
      "Zombie",
    ],
  },
  ru: {
    easy: [
      "Ангел",
      "Глазное яблоко",
      "Пицца",
      "Сердитый",
      "Фейерверк",
      "Тыква",
      "Младенец",
      "Цветок",
      "Радуга",
      "Борода",
      "Летающая тарелка",
      "Перерабатывать",
      "Библия",
      "Жираф",
      "Песочный замок",
      "Бикини",
      "Очки",
      "Снежинка",
      "Книга",
      "Туфель на высоком каблуке",
      "Лестница",
      "Ведро",
      "Мороженое",
      "Морская звезда",
      "Шмель",
      "Иглу",
      "Клубника",
      "Бабочка",
      "Божья коровка",
      "Солнце",
      "Камера",
      "Лампа",
      "Шина",
      "Кошка",
      "Лев",
      "Тост",
      "Церковь",
      "Почтовый ящик",
      "Туалет",
      "Кофе",
      "Гвоздь",
      "Зубная щетка",
      "Мелок",
      "Ночь",
      "Зубная паста",
      "Собака",
      "Нос",
      "Грузовик",
      "Дельфин",
      "Олимпийские игры",
      "Ваза",
      "Яйцо",
      "Орео",
      "Волейбол",
      "Эйфелева башня",
      "Арахис",
      "Колесо",
    ],
    medium: [
      "Авраам Линкольн",
      "Поцелуй",
      "Косички",
      "Мозг",
      "Котёнок",
      "Игровая площадка",
      "Пенистая ванна",
      "Киви",
      "Тыквенный пирог",
      "Пряжка",
      "Помада",
      "Капля дождя",
      "Автобус",
      "Омар",
      "Робот",
      "Автомобильная авария",
      "Леденец",
      "Саламандра",
      "Замок",
      "Магнит",
      "Тапочка",
      "Бензопила",
      "Мегафон",
      "Снежок",
      "Цирковой шатер",
      "Русалка",
      "Разбрызгиватель",
      "Компьютер",
      "Минивэн",
      "Статуя Свободы",
      "Детская кроватка",
      "Гора Рашмор",
      "Головастик",
      "Дракон",
      "Музыка",
      "Типи",
      "Гантель",
      "Северный полюс",
      "Телескоп",
      "Угорь",
      "Медсестра",
      "Томат",
      "Слон",
      "Лук",
      "Поезд",
      "Чёртово колесо",
      "Сова",
      "Трёхколёсный велосипед",
      "Флаг",
      "Соска",
      "Пачка",
      "Гольф",
      "Монета",
      "Зонтик",
      "Ненужная почта",
      "Пианино",
      "Морж",
    ],
    hard: [
      "Чердак",
      "Клей",
      "Карманные часы",
      "Заднее сиденье",
      "Детский стульчик",
      "Рок-группа",
      "День рождения",
      "Хоккей",
      "Сасквоч",
      "Чёрная дыра",
      "Отель",
      "Яичница-болтунья",
      "Буран",
      "Скакалка",
      "Ремень безопасности",
      "Буррито",
      "Коала",
      "Прыжки",
      "Капитан",
      "Лепрекон",
      "Солнечное затмение",
      "Люстра",
      "Свет",
      "Космос",
      "Детская кроватка",
      "Маска",
      "Стетоскоп",
      "Круизный лайнер",
      "Механик",
      "Аист",
      "Танец",
      "Мама",
      "Солнечный ожог",
      "Дезодорант",
      "Мистер Картофельная Голова",
      "Нить",
      "Эйнштейн",
      "Нарвал",
      "Турист",
      "Фейсбук",
      "Опера",
      "Батут",
      "Жар",
      "Колготки",
      "Соединённые Штаты",
      "Квартира",
      "Бумажная тарелка",
      "Вселенная",
      "Рамка",
      "Фото",
      "Вай-фай",
      "Полнолуние",
      "Пилигрим",
      "Зевок",
      "Игра",
      "Пират",
      "Зомби",
    ],
  },
  es: {
    easy: [
      "Ángel",
      "Ojo",
      "Pizza",
      "Enojado",
      "Fuegos artificiales",
      "Calabaza",
      "Bebé",
      "Flor",
      "Arcoíris",
      "Barba",
      "Platillo volador",
      "Reciclar",
      "Biblia",
      "Jirafa",
      "Castillo de arena",
      "Bikini",
      "Gafas",
      "Copo de nieve",
      "Libro",
      "Tacón alto",
      "Escaleras",
      "Cubo",
      "Cono de helado",
      "Estrella de mar",
      "Abejorro",
      "Iglú",
      "Fresa",
      "Mariposa",
      "Mariquita",
      "Sol",
      "Cámara",
      "Lámpara",
      "Neumático",
      "Gato",
      "León",
      "Tostada",
      "Iglesia",
      "Buzón",
      "Inodoro",
      "Café",
      "Uña",
      "Cepillo de dientes",
      "Crayón",
      "Noche",
      "Pasta de dientes",
      "Perro",
      "Nariz",
      "Camión",
      "Delfín",
      "Olimpiadas",
      "Jarrón",
      "Huevo",
      "Oreo",
      "Voleibol",
      "Torre Eiffel",
      "Cacahuate",
      "Rueda",
    ],
    medium: [
      "Abraham Lincoln",
      "Beso",
      "Coletas",
      "Cerebro",
      "Gatito",
      "Parque infantil",
      "Baño de burbujas",
      "Kiwi",
      "Pastel de calabaza",
      "Hebilla",
      "Lápiz labial",
      "Gota de lluvia",
      "Autobús",
      "Langosta",
      "Robot",
      "Accidente de coche",
      "Piruleta",
      "Salamandra",
      "Castillo",
      "Imán",
      "Zapatilla",
      "Motosierra",
      "Megáfono",
      "Bola de nieve",
      "Carpa de circo",
      "Sirena",
      "Aspersor",
      "Computadora",
      "Miniván",
      "Estatua de la Libertad",
      "Cuna",
      "Monte Rushmore",
      "Renacuajo",
      "Dragón",
      "Música",
      "Tienda de campaña",
      "Mancuerna",
      "Polo Norte",
      "Telescopio",
      "Anguila",
      "Enfermera",
      "Tomate",
      "Elefante",
      "Cebolla",
      "Tren",
      "Noria",
      "Búho",
      "Triciclo",
      "Bandera",
      "Chupete",
      "Tutu",
      "Golf",
      "Centavo",
      "Paraguas",
      "Correo basura",
      "Piano",
      "Morsa",
    ],
    hard: [
      "Ático",
      "Pegamento",
      "Reloj de bolsillo",
      "Asiento trasero",
      "Silla alta",
      "Banda de rock",
      "Cumpleaños",
      "Hockey",
      "Sasquatch",
      "Agujero negro",
      "Hotel",
      "Huevos revueltos",
      "Tormenta de nieve",
      "Cuerda para saltar",
      "Cinturón de seguridad",
      "Burrito",
      "Koala",
      "Saltar",
      "Capitán",
      "Duende",
      "Eclipse solar",
      "Candelabro",
      "Luz",
      "Espacio",
      "Cuna",
      "Máscara",
      "Estetoscopio",
      "Barco de crucero",
      "Mecánico",
      "Cigüeña",
      "Baile",
      "Mamá",
      "Quemadura solar",
      "Desodorante",
      "Señor Cara de Papa",
      "Hilo",
      "Einstein",
      "Narval",
      "Turista",
      "Facebook",
      "Ópera",
      "Trampolín",
      "Fiebre",
      "Medias",
      "Estados Unidos",
      "Plano",
      "Plato de papel",
      "Universo",
      "Marco",
      "Foto",
      "Wi-Fi",
      "Luna llena",
      "Pilgrim",
      "Bostezo",
      "Juego",
      "Pirata",
      "Zombi",
    ],
  },
  pt: {
    easy: [
      "Anjo",
      "Olho",
      "Pizza",
      "Bravo",
      "Fogos de artifício",
      "Abóbora",
      "Bebê",
      "Flor",
      "Arco-íris",
      "Barba",
      "Disco voador",
      "Reciclar",
      "Bíblia",
      "Girafa",
      "Castelo de areia",
      "Biquíni",
      "Óculos",
      "Floco de neve",
      "Livro",
      "Salto alto",
      "Escadas",
      "Balde",
      "Casquinha de sorvete",
      "Estrela-do-mar",
      "Abelha",
      "Iglu",
      "Morango",
      "Borboleta",
      "Joaninha",
      "Sol",
      "Câmera",
      "Lâmpada",
      "Pneu",
      "Gato",
      "Leão",
      "Torrada",
      "Igreja",
      "Caixa de correio",
      "Vaso sanitário",
      "Café",
      "Unha",
      "Escova de dentes",
      "Giz de cera",
      "Noite",
      "Creme dental",
      "Cachorro",
      "Nariz",
      "Caminhão",
      "Golfinho",
      "Olimpíadas",
      "Vaso",
      "Ovo",
      "Oreo",
      "Vôlei",
      "Torre Eiffel",
      "Amendoim",
      "Roda",
    ],
    medium: [
      "Abraham Lincoln",
      "Beijo",
      "Rabo de cavalo",
      "Cérebro",
      "Gatinho",
      "Parque infantil",
      "Banho de espuma",
      "Kiwi",
      "Torta de abóbora",
      "Fivela",
      "Batom",
      "Gota de chuva",
      "Ônibus",
      "Lagosta",
      "Robô",
      "Acidente de carro",
      "Pirulito",
      "Salamandra",
      "Castelo",
      "Ímã",
      "Chinelo",
      "Serra elétrica",
      "Megafone",
      "Bola de neve",
      "Tenda de circo",
      "Sereia",
      "Sprinkler",
      "Computador",
      "Minivan",
      "Estátua da Liberdade",
      "Berço",
      "Monte Rushmore",
      "Girino",
      "Dragão",
      "Música",
      "Tenda",
      "Halter",
      "Polo Norte",
      "Telescópio",
      "Enguia",
      "Enfermeira",
      "Tomate",
      "Elefante",
      "Cebola",
      "Trem",
      "Roda-gigante",
      "Coruja",
      "Triciclo",
      "Bandeira",
      "Chupeta",
      "Tutu",
      "Golfe",
      "Moeda",
      "Guarda-chuva",
      "Correio indesejado",
      "Piano",
      "Morsa",
    ],
    hard: [
      "Sótão",
      "Cola",
      "Relógio de bolso",
      "Banco traseiro",
      "Cadeira alta",
      "Banda de rock",
      "Aniversário",
      "Hóquei",
      "Pé grande",
      "Buraco negro",
      "Hotel",
      "Ovo mexido",
      "Tempestade de neve",
      "Corda",
      "Cinto de segurança",
      "Burrito",
      "Coala",
      "Pular",
      "Capitão",
      "Duende",
      "Eclipse solar",
      "Candelabro",
      "Luz",
      "Espaço",
      "Berço",
      "Máscara",
      "Estetoscópio",
      "Navio de cruzeiro",
      "Mecânico",
      "Cegonha",
      "Dança",
      "Mãe",
      "Queimadura solar",
      "Desodorante",
      "Sr. Cabeça de Batata",
      "Linha",
      "Einstein",
      "Narval",
      "Turista",
      "Facebook",
      "Ópera",
      "Trampolim",
      "Febre",
      "Meia-calça",
      "Estados Unidos",
      "Apartamento",
      "Prato de papel",
      "Universo",
      "Moldura",
      "Foto",
      "Wi-Fi",
      "Lua cheia",
      "Peregrino",
      "Bocejo",
      "Jogo",
      "Pirata",
      "Zumbi",
    ],
  },
  cn: {
    easy: [
      "天使",
      "眼球",
      "披萨",
      "生气",
      "烟花",
      "南瓜",
      "婴儿",
      "花",
      "彩虹",
      "胡子",
      "飞碟",
      "回收",
      "圣经",
      "长颈鹿",
      "沙堡",
      "比基尼",
      "眼镜",
      "雪花",
      "书",
      "高跟鞋",
      "楼梯",
      "桶",
      "冰淇淋蛋筒",
      "海星",
      "大黄蜂",
      "冰屋",
      "草莓",
      "蝴蝶",
      "瓢虫",
      "太阳",
      "相机",
      "灯",
      "轮胎",
      "猫",
      "狮子",
      "吐司",
      "教堂",
      "邮箱",
      "厕所",
      "咖啡",
      "钉子",
      "牙刷",
      "蜡笔",
      "夜晚",
      "牙膏",
      "狗",
      "鼻子",
      "卡车",
      "海豚",
      "奥运会",
      "花瓶",
      "鸡蛋",
      "奥利奥",
      "排球",
      "埃菲尔铁塔",
      "花生",
      "轮子",
    ],
    medium: [
      "亚伯拉罕·林肯",
      "亲吻",
      "辫子",
      "大脑",
      "小猫",
      "操场",
      "泡泡浴",
      "奇异果",
      "南瓜派",
      "扣子",
      "口红",
      "雨滴",
      "公共汽车",
      "龙虾",
      "机器人",
      "车祸",
      "棒棒糖",
      "蝾螈",
      "城堡",
      "磁铁",
      "拖鞋",
      "电锯",
      "扩音器",
      "雪球",
      "马戏团帐篷",
      "美人鱼",
      "洒水器",
      "电脑",
      "小型货车",
      "自由女神像",
      "婴儿床",
      "拉什莫尔山",
      "蝌蚪",
      "龙",
      "音乐",
      "圆锥帐篷",
      "哑铃",
      "北极",
      "望远镜",
      "鳗鱼",
      "护士",
      "西红柿",
      "大象",
      "洋葱",
      "火车",
      "摩天轮",
      "猫头鹰",
      "三轮车",
      "旗子",
      "奶嘴",
      "芭蕾舞短裙",
      "高尔夫",
      "便士",
      "雨伞",
      "垃圾邮件",
      "钢琴",
      "海象",
    ],

    hard: [
      "阁楼",
      "胶水",
      "怀表",
      "后座",
      "高脚椅",
      "摇滚乐队",
      "生日",
      "曲棍球",
      "大脚怪",
      "黑洞",
      "酒店",
      "炒蛋",
      "暴风雪",
      "跳绳",
      "安全带",
      "卷饼",
      "考拉",
      "跳跃",
      "船长",
      "妖精",
      "日食",
      "吊灯",
      "光",
      "太空",
      "婴儿床",
      "面具",
      "听诊器",
      "游轮",
      "机械师",
      "鹳",
      "舞蹈",
      "妈妈",
      "晒伤",
      "除臭剂",
      "土豆头先生",
      "线",
      "爱因斯坦",
      "独角鲸",
      "游客",
      "脸书",
      "歌剧",
      "蹦床",
      "发烧",
      "连裤袜",
      "美国",
      "公寓",
      "纸盘",
      "宇宙",
      "相框",
      "照片",
      "Wi-Fi",
      "满月",
      "朝圣者",
      "打哈欠",
      "游戏",
      "海盗",
      "僵尸",
    ],
  },
}
