export const words = {
  en: {
    easy: [
      "Angel",
      "Eyeball",
      "Pizza",
      "Angry",
      "Fireworks",
      "Pumpkin",
      "Baby",
      "Flower",
      "Rainbow",
      "Beard",
      "Flying saucer",
      "Recycle",
      "Bible",
      "Giraffe",
      "Sand castle",
      "Bikini",
      "Glasses",
      "Snowflake",
      "Book",
      "High heel",
      "Stairs",
      "Bucket",
      "Ice cream cone",
      "Starfish",
      "Bumblebee",
      "Igloo",
      "Strawberry",
      "Butterfly",
      "Ladybug",
      "Sun",
      "Camera",
      "Lamp",
      "Tire",
      "Cat",
      "Lion",
      "Toast",
      "Church",
      "Mailbox",
      "Toilet",
      "Coffee",
      "Nail",
      "Toothbrush",
      "Crayon",
      "Night",
      "Toothpaste",
      "Dog",
      "Nose",
      "Truck",
      "Dolphin",
      "Olympics",
      "Vase",
      "Egg",
      "Oreo",
      "Volleyball",
      "Eiffel Tower",
      "Peanut",
      "Wheel",
    ],
    medium: [
      "Abraham Lincoln",
      "Kiss",
      "Pigtails",
      "Brain",
      "Kitten",
      "Playground",
      "Bubble bath",
      "Kiwi",
      "Pumpkin pie",
      "Buckle",
      "Lipstick",
      "Raindrop",
      "Bus",
      "Lobster",
      "Robot",
      "Car accident",
      "Lollipop",
      "Salamander",
      "Castle",
      "Magnet",
      "Slipper",
      "Chainsaw",
      "Megaphone",
      "Snowball",
      "Circus tent",
      "Mermaid",
      "Sprinkler",
      "Computer",
      "Minivan",
      "Statue of Liberty",
      "Crib",
      "Mount Rushmore",
      "Tadpole",
      "Dragon",
      "Music",
      "Teepee",
      "Dumbbell",
      "North Pole",
      "Telescope",
      "Eel",
      "Nurse",
      "Tomato",
      "Elephant",
      "Onion",
      "Train",
      "Ferris wheel",
      "Owl",
      "Tricycle",
      "Flag",
      "Pacifier",
      "Tutu",
      "Golf",
      "Penny",
      "Umbrella",
      "Junk mail",
      "Piano",
      "Walrus",
    ],
    hard: [
      "Attic",
      "Glue",
      "Pocket watch",
      "Back seat",
      "High chair",
      "Rock band",
      "Birthday",
      "Hockey",
      "Sasquatch",
      "Black hole",
      "Hotel",
      "Scrambled eggs",
      "Blizzard",
      "Jump rope",
      "Seat belt",
      "Burrito",
      "Koala",
      "Skipping",
      "Captain",
      "Leprechaun",
      "Solar eclipse",
      "Chandelier",
      "Light",
      "Space",
      "Crib",
      "Mask",
      "Stethoscope",
      "Cruise ship",
      "Mechanic",
      "Stork",
      "Dance",
      "Mom",
      "Sunburn",
      "Deodorant",
      "Mr. Potato Head",
      "Thread",
      "Einstein",
      "Narwhal",
      "Tourist",
      "Facebook",
      "Opera",
      "Trampoline",
      "Fever",
      "Pantyhose",
      "United States",
      "Flat",
      "Paper plate",
      "Universe",
      "Frame",
      "Photo",
      "Wi-Fi",
      "Full moon",
      "Pilgrim",
      "Yawn",
      "Game",
      "Pirate",
      "Zombie",
    ],
  },
}
